name: Auto Deploy AI Trading Assistant

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Deploy to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "AI_Bot"
          git add .
          git commit -m "Auto-update AI Trading Assistant" || echo "No changes to commit"
          git push origin main
      
        ssh -T git@github.com  

        
